---
name: Text-FixEOL
version: 1.04
author:
  - Benjamin Franz <snowhare@nihongo.org>
abstract: Canonicalizes mixed convention EOL/EOF
license: perl
requires:
  Test::More: 0
build_requires:
  Test::More: 0
provides:
  Text::FixEOL:
    file: lib/Text/FixEOL.pm
    version: 1.04
generated_by: Module::Build version 0.261
