---
name: Text-FixEOL
version: 1.01
author:
  - Benjamin Franz <snowhare@nihongo.org>
abstract: Canonicalizes mixed convention EOL/EOF
license: perl
requires:
  Test::More: 0.54
  Test::NoWarnings: 0.07
build_requires:
  Test::More: 0.54
  Test::NoWarnings: 0.07
provides:
  Text::FixEOL:
    file: lib/Text/FixEOL.pm
    version: 1.01
generated_by: Module::Build version 0.261
